medie: main.o studentList.o 
	gcc -o medie main.o studentList.o 

main.o: main.c listaStudenti.h
	gcc -c -o main.o main.c

studentList.o: listaStudenti.c 
	gcc -c -o studentList.o listaStudenti.c





